# Generated by Django 3.1.3 on 2020-11-13 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSheetLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_character_builder_rules.charactersheetline_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='CharacterSheetMultipleLine',
            fields=[
                ('charactersheetline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character_builder_rules.charactersheetline')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('character_builder_rules.charactersheetline',),
        ),
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('charactersheetmultipleline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character_builder_rules.charactersheetmultipleline')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('character_builder_rules.charactersheetmultipleline',),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('charactersheetmultipleline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character_builder_rules.charactersheetmultipleline')),
                ('name', models.CharField(max_length=256)),
                ('equipment_type', models.CharField(choices=[('Object', 'Objet'), ('Effect', 'Effet')], default='Object', max_length=20)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('character_builder_rules.charactersheetmultipleline',),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('charactersheetmultipleline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character_builder_rules.charactersheetmultipleline')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('character_builder_rules.charactersheetmultipleline',),
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('charactersheetline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character_builder_rules.charactersheetline')),
                ('name', models.CharField(max_length=128)),
                ('mother_race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inherited_mother_race', to='character_builder_rules.race')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('character_builder_rules.charactersheetline',),
        ),
    ]
