# Generated by Django 3.1.3 on 2020-11-13 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder_rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipentEffect',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character_builder_rules.equipment')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('character_builder_rules.equipment',),
        ),
        migrations.CreateModel(
            name='EquipmentObject',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character_builder_rules.equipment')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('character_builder_rules.equipment',),
        ),
        migrations.AlterModelOptions(
            name='charactersheetline',
            options={'verbose_name': '1 - Element de fiche perso', 'verbose_name_plural': '1 - Elements de fiches perso'},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_type',
        ),
    ]
