# Generated by Django 3.1.3 on 2020-11-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttributeType',
        ),
    ]
